### PR TITLE
removed main from NDBrandLayout

### PR DESCRIPTION
**Pull request by pweikel**
This is a part of [added unique main sectioning element](https://github.com/ndlib/marble-web/pull/97) in marble-web

### CODE REVIEW

**Review by danthewolfe — COMMENTED** [review]
I'm okay with changing this tag from `<main />` to `<section />`, but I feel like we should probably leave the id attached to this location in the Layout. Requiring individual pages to remember to implement a specific named id seems like it could be problematic and a detail that could be easily missed resulting in broken behavior.

Thoughts @jonhartzler

**Comment by pweikel** [comment]
> I'm okay with changing this tag from `<main />` to `<section />`, but I feel like we should probably leave the id attached to this location in the Layout. Requiring individual pages to remember to implement a specific named id seems like it could be problematic and a detail that could be easily missed resulting in broken behavior.
> 
> Thoughts @jonhartzler

So in the marble-web repo, where the <main /> was added in [this PR](https://github.com/ndlib/marble-web/pull/97), I have include the #mainContent id. By placing it here it will direct the user to the main section of the page that contains the content. This makes it easier to access when navigating by keyboard or using VoiceOver.

**Comment by danthewolfe** [comment]
> So in the marble-web repo, where the `<main /> `was added in [this PR](https://github.com/ndlib/marble-web/pull/97), I have included the #mainContent ID. By placing it [here](https://github.com/ndlib/marble-web/pull/97/files#diff-2a58df35170c5ef62e5f0e683734635737407f45ca76b70c8113aea19a59c412R139), the user is directed to the main section of the page that contains the beginning of the content. This makes it easier to access when navigating by keyboard or using VoiceOver.

Right, that is part of my point. This functionality is no longer self contained. I guess the problem was that the "skip to main" button doesn't always get the user to the actual main content, which is problematic from an accessibility point of view, but the problem with putting the specific named id on each page becomes a larger problem of maintainability. For this to work and not produce an error that id needs to be on every page. You've already added it to 12-13 pages. Did you get every page in the site? Including the dynamic pages for users and portfolios? Does this feature still work on Inquisitions? What happens when we add additional pages? This requirement to add a specific id is not documented anywhere and is likely to be forgotten, creating technical debt. 

This isn't a unique problem in terms of maintainability, we have this problem with regard to several features on the site, but this is the point where we need to be eliminating "assumed knowledge" and "technical debt" as much as possible. Is there a way we can get closer to the real main content without having to touch every page?

**Comment by jonhartzler** [comment]
@danthewolfe I don't think there is a way without a total and complicated rearchitecting of the class to get closer to the main.   My preference with the tag is really that it gets used correctly which I think is more situational than standardized.  So I guess I am in favor of this change.   As far as the skip to main.  It seems to be gone now?   But it will not work anyway until we can update the okta lib to stop grabbing everything after # and then failing.

**Pull request merged**
